# Generated by Django 4.0.3 on 2023-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.TextField(default='테스트'),
            preserve_default=False,
        ),
    ]
