# Generated by Django 5.0.1 on 2024-01-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.TextField()),
                ('url', models.URLField()),
                ('img', models.URLField()),
            ],
        ),
    ]
